## Machine learning Algorithm Trader

In this project, we will be using the OANDA v20 REST API  

<img style="float: left;" src="./images/api.png">

# Why forex over stocks?


![3advantage](./images/lvts.png)

### Liquidity  
The forex market is the largest and most liquid financial market. Daily activity often exceeds 4 trillion USD, with over 1.5 trillion of that conducted in the form of spot trading.


### Volatility  
Volatility boosts opportunity due to exchange rate fluctuations. Forex trading operates 24 hours a day, 5 days a week. The greatest liquidity occurs when operational hours in multiple time zones overlap.


### Tight Spreads  
Spreads in the forex market tend to be tighter (less), than the spreads applied to other, securities such as stocks. This makes OTC forex trading one of the most cost - effective means of investment trading.

In [50]:
#python packages required

# pip install v20  #OANDA V20 API
# pip install ujson
# pip install PyYAML
# pip install --index-url https://test.pypi.org/simple/ #tpqoa wrap up package

In [51]:
import pandas as pd
import tpqoa

In [52]:
#sensitive ID and password have been gitignored you will need to create your own config file 


api = tpqoa.tpqoa("oanda.cfg")

In [53]:
api.get_account_summary()

{'id': '101-003-23224294-001',
 'alias': 'Primary',
 'currency': 'SGD',
 'balance': '100000.0086',
 'createdByUserID': 23224294,
 'createdTime': '2022-09-13T12:16:27.974338285Z',
 'guaranteedStopLossOrderMode': 'ALLOWED',
 'pl': '-267.7014',
 'resettablePL': '-267.7014',
 'resettablePLTime': '0',
 'financing': '0.0',
 'commission': '0.0',
 'guaranteedExecutionFees': '0.0',
 'marginRate': '0.05',
 'openTradeCount': 0,
 'openPositionCount': 0,
 'pendingOrderCount': 0,
 'hedgingEnabled': False,
 'unrealizedPL': '0.0',
 'NAV': '100000.0086',
 'marginUsed': '0.0',
 'marginAvailable': '100000.0086',
 'positionValue': '0.0',
 'marginCloseoutUnrealizedPL': '0.0',
 'marginCloseoutNAV': '100000.0086',
 'marginCloseoutMarginUsed': '0.0',
 'marginCloseoutPercent': '0.0',
 'marginCloseoutPositionValue': '0.0',
 'withdrawalLimit': '100000.0086',
 'marginCallMarginUsed': '0.0',
 'marginCallPercent': '0.0',
 'lastTransactionID': '20'}

In [54]:
#ensure the accunt type is the OANDA demo account
api.account_type

'practice'

In [55]:
api.account_id

'101-003-23224294-001'

In [56]:
api.get_instruments()

[('Copper', 'XCU_USD'),
 ('Wheat', 'WHEAT_USD'),
 ('NZD/SGD', 'NZD_SGD'),
 ('US SPX 500', 'SPX500_USD'),
 ('USD/NOK', 'USD_NOK'),
 ('UK 100', 'UK100_GBP'),
 ('AUD/NZD', 'AUD_NZD'),
 ('Silver', 'XAG_USD'),
 ('EUR/HUF', 'EUR_HUF'),
 ('Silver/EUR', 'XAG_EUR'),
 ('Litecoin', 'LTC_USD'),
 ('Silver/GBP', 'XAG_GBP'),
 ('NZD/USD', 'NZD_USD'),
 ('USD/CNH', 'USD_CNH'),
 ('CHF/ZAR', 'CHF_ZAR'),
 ('GBP/NZD', 'GBP_NZD'),
 ('US 10Y T-Note', 'USB10Y_USD'),
 ('Hong Kong 33', 'HK33_HKD'),
 ('US 5Y T-Note', 'USB05Y_USD'),
 ('US 2Y T-Note', 'USB02Y_USD'),
 ('Bund', 'DE10YB_EUR'),
 ('US Russ 2000', 'US2000_USD'),
 ('US T-Bond', 'USB30Y_USD'),
 ('USD/CAD', 'USD_CAD'),
 ('ZAR/JPY', 'ZAR_JPY'),
 ('Silver/JPY', 'XAG_JPY'),
 ('Ether', 'ETH_USD'),
 ('SGD/JPY', 'SGD_JPY'),
 ('GBP/ZAR', 'GBP_ZAR'),
 ('USD/JPY', 'USD_JPY'),
 ('EUR/TRY', 'EUR_TRY'),
 ('Bitcoin', 'BTC_USD'),
 ('EUR/CZK', 'EUR_CZK'),
 ('EUR/JPY', 'EUR_JPY'),
 ('Taiwan Index', 'TWIX_USD'),
 ('AUD/SGD', 'AUD_SGD'),
 ('Silver/NZD', 'XAG_NZD'),
 ('West Texas Oil', 'WTICO_USD'),
 ('Silver/AUD', 'XAG_AUD'),
 ('EUR/NZD', 'EUR_NZD'),
 ('GBP/HKD', 'GBP_HKD'),
 ('CHF/JPY', 'CHF_JPY'),
 ('Gold/AUD', 'XAU_AUD'),
 ('EUR/HKD', 'EUR_HKD'),
 ('Gold/HKD', 'XAU_HKD'),
 ('Gold/JPY', 'XAU_JPY'),
 ('USD/THB', 'USD_THB'),
 ('GBP/CHF', 'GBP_CHF'),
 ('CAD/JPY', 'CAD_JPY'),
 ('NZD/CHF', 'NZD_CHF'),
 ('Spain 35', 'ESPIX_EUR'),
 ('AUD/HKD', 'AUD_HKD'),
 ('Silver/HKD', 'XAG_HKD'),
 ('USD/CHF', 'USD_CHF'),
 ('Silver/CHF', 'XAG_CHF'),
 ('Bitcoin Cash', 'BCH_USD'),
 ('AUD/USD', 'AUD_USD'),
 ('GBP/JPY', 'GBP_JPY'),
 ('USD/TRY', 'USD_TRY'),
 ('US Nas 100', 'NAS100_USD'),
 ('TRY/JPY', 'TRY_JPY'),
 ('USD/SGD', 'USD_SGD'),
 ('EUR/SEK', 'EUR_SEK'),
 ('HKD/JPY', 'HKD_JPY'),
 ('AUD/CHF', 'AUD_CHF'),
 ('Gold/Silver', 'XAU_XAG'),
 ('SGD/CHF', 'SGD_CHF'),
 ('Soybeans', 'SOYBN_USD'),
 ('Corn', 'CORN_USD'),
 ('USD/PLN', 'USD_PLN'),
 ('GBP/AUD', 'GBP_AUD'),
 ('Gold/SGD', 'XAU_SGD'),
 ('AUD/JPY', 'AUD_JPY'),
 ('EUR/ZAR', 'EUR_ZAR'),
 ('China H Shares', 'CHINAH_HKD'),
 ('Singapore 30', 'SG30_SGD'),
 ('EUR/USD', 'EUR_USD'),
 ('EUR/CAD', 'EUR_CAD'),
 ('USD/HUF', 'USD_HUF'),
 ('Netherlands 25', 'NL25_EUR'),
 ('EUR/CHF', 'EUR_CHF'),
 ('UK 10Y Gilt', 'UK10YB_GBP'),
 ('NZD/CAD', 'NZD_CAD'),
 ('EUR/SGD', 'EUR_SGD'),
 ('USD/INR', 'USD_INR'),
 ('Gold/NZD', 'XAU_NZD'),
 ('Gold/GBP', 'XAU_GBP'),
 ('NZD/JPY', 'NZD_JPY'),
 ('CHF/HKD', 'CHF_HKD'),
 ('Australia 200', 'AU200_AUD'),
 ('USD/DKK', 'USD_DKK'),
 ('EUR/AUD', 'EUR_AUD'),
 ('Gold/CAD', 'XAU_CAD'),
 ('Gold/CHF', 'XAU_CHF'),
 ('Japan 225', 'JP225_USD'),
 ('Silver/CAD', 'XAG_CAD'),
 ('USD/ZAR', 'USD_ZAR'),
 ('USD/CZK', 'USD_CZK'),
 ('China A50', 'CN50_USD'),
 ('Europe 50', 'EU50_EUR'),
 ('Silver/SGD', 'XAG_SGD'),
 ('France 40', 'FR40_EUR'),
 ('GBP/SGD', 'GBP_SGD'),
 ('USD/SEK', 'USD_SEK'),
 ('USD/MXN', 'USD_MXN'),
 ('GBP/USD', 'GBP_USD'),
 ('EUR/DKK', 'EUR_DKK'),
 ('Natural Gas', 'NATGAS_USD'),
 ('CAD/CHF', 'CAD_CHF'),
 ('EUR/GBP', 'EUR_GBP'),
 ('CAD/HKD', 'CAD_HKD'),
 ('Switzerland 20', 'CH20_CHF'),
 ('Brent Crude Oil', 'BCO_USD'),
 ('EUR/NOK', 'EUR_NOK'),
 ('Gold', 'XAU_USD'),
 ('Palladium', 'XPD_USD'),
 ('Platinum', 'XPT_USD'),
 ('GBP/CAD', 'GBP_CAD'),
 ('Gold/EUR', 'XAU_EUR'),
 ('Germany 30', 'DE30_EUR'),
 ('NZD/HKD', 'NZD_HKD'),
 ('GBP/PLN', 'GBP_PLN'),
 ('US Wall St 30', 'US30_USD'),
 ('Japan 225 (JPY)', 'JP225Y_JPY'),
 ('EUR/PLN', 'EUR_PLN'),
 ('Sugar', 'SUGAR_USD'),
 ('AUD/CAD', 'AUD_CAD'),
 ('USD/HKD', 'USD_HKD'),
 ('CAD/SGD', 'CAD_SGD')]

In [57]:
instr = api.get_instruments()

In [58]:
len(instr)

129

In [59]:
instr[0]

('Copper', 'XCU_USD')

## Getting Historical Data

In [60]:
#lets see how to use .get_history 
help(api.get_history)

Help on method get_history in module tpqoa.tpqoa:

get_history(instrument, start, end, granularity, price) method of tpqoa.tpqoa.tpqoa instance
    Retrieves historical data for instrument.

    Parameters
    ==========
    instrument: string
        valid instrument name
    start, end: datetime, str
        Python datetime or string objects for start and end
    granularity: string
        a string like 'S5', 'M1' or 'D'
    price: string
        one of 'A' (ask) or 'B' (bid)

    Returns
    =======
    data: pd.DataFrame
        pandas DataFrame object with data

In [61]:
api.get_history("EUR_USD", "2022-08-03", "2022-08-05", "H1", "A")

,volume,complete,o,h,l,c
time,,,,,,
2022-08-03 00:00:00+00:00,4316,True,1.01575,1.01652,1.01508,1.01590
2022-08-03 01:00:00+00:00,4765,True,1.01593,1.01719,1.01576,1.01716
2022-08-03 02:00:00+00:00,3932,True,1.01717,1.01831,1.01695,1.01812
2022-08-03 03:00:00+00:00,3507,True,1.01813,1.01947,1.01782,1.01922
2022-08-03 04:00:00+00:00,3764,True,1.01922,1.01942,1.01821,1.01867
2022-08-03 05:00:00+00:00,3595,True,1.01868,1.01879,1.01752,1.01771
2022-08-03 06:00:00+00:00,6233,True,1.01766,1.01809,1.01549,1.01605
2022-08-03 07:00:00+00:00,8249,True,1.01607,1.01921,1.01602,1.01789
2022-08-03 08:00:00+00:00,6491,True,1.01792,1.01898,1.01792,1.01889
2022-08-03 09:00:00+00:00,5513,True,1.01887,1.01988,1.01820,1.01871
2022-08-03 10:00:00+00:00,6506,True,1.01872,1.02012,1.01795,1.01885
2022-08-03 11:00:00+00:00,6671,True,1.01882,1.02111,1.01810,1.01849
2022-08-03 12:00:00+00:00,7709,True,1.01852,1.01977,1.01807,1.01870
2022-08-03 13:00:00+00:00,7491,True,1.01868,1.01884,1.01663,1.01713
2022-08-03 14:00:00+00:00,15605,True,1.01715,1.01715,1.01260,1.01311
2022-08-03 15:00:00+00:00,7960,True,1.01310,1.01473,1.01235,1.01454
2022-08-03 16:00:00+00:00,6200,True,1.01455,1.01674,1.01409,1.01509
2022-08-03 17:00:00+00:00,3085,True,1.01509,1.01608,1.01493,1.01586
2022-08-03 18:00:00+00:00,3366,True,1.01586,1.01613,1.01501,1.01557
2022-08-03 19:00:00+00:00,3328,True,1.01553,1.01747,1.01549,1.01693
2022-08-03 20:00:00+00:00,2147,True,1.01697,1.01732,1.01684,1.01703
2022-08-03 21:00:00+00:00,208,True,1.01710,1.01726,1.01689,1.01713
2022-08-03 22:00:00+00:00,1955,True,1.01713,1.01727,1.01571,1.01628
2022-08-03 23:00:00+00:00,1358,True,1.01628,1.01634,1.01575,1.01575
2022-08-04 00:00:00+00:00,3582,True,1.01572,1.01672,1.01550,1.01659
2022-08-04 01:00:00+00:00,3489,True,1.01657,1.01770,1.01622,1.01701
2022-08-04 02:00:00+00:00,2246,True,1.01700,1.01737,1.01624,1.01656
2022-08-04 03:00:00+00:00,1888,True,1.01658,1.01715,1.01612,1.01637
2022-08-04 04:00:00+00:00,1949,True,1.01637,1.01683,1.01619,1.01651
2022-08-04 05:00:00+00:00,3120,True,1.01649,1.01748,1.01626,1.01639
2022-08-04 06:00:00+00:00,5102,True,1.01641,1.01733,1.01575,1.01689
2022-08-04 07:00:00+00:00,6953,True,1.01690,1.01872,1.01672,1.01799
2022-08-04 08:00:00+00:00,5354,True,1.01797,1.01950,1.01753,1.01925
2022-08-04 09:00:00+00:00,4937,True,1.01924,1.01988,1.01864,1.01895
2022-08-04 10:00:00+00:00,4682,True,1.01894,1.01972,1.01862,1.01914
2022-08-04 11:00:00+00:00,10910,True,1.01912,1.01967,1.01612,1.01768
2022-08-04 12:00:00+00:00,10518,True,1.01764,1.01960,1.01663,1.01889
2022-08-04 13:00:00+00:00,9768,True,1.01891,1.01973,1.01741,1.01924
2022-08-04 14:00:00+00:00,9939,True,1.01927,1.02130,1.01869,1.02124
2022-08-04 15:00:00+00:00,7623,True,1.02125,1.02347,1.02069,1.02230
2022-08-04 16:00:00+00:00,5666,True,1.02231,1.02404,1.02188,1.02376
2022-08-04 17:00:00+00:00,3536,True,1.02374,1.02435,1.02314,1.02383
2022-08-04 18:00:00+00:00,3297,True,1.02381,1.02511,1.02373,1.02509
2022-08-04 19:00:00+00:00,2967,True,1.02508,1.02547,1.02449,1.02463
2022-08-04 20:00:00+00:00,1214,True,1.02459,1.02482,1.02434,1.02478
2022-08-04 21:00:00+00:00,343,True,1.02518,1.02520,1.02471,1.02473
2022-08-04 22:00:00+00:00,1509,True,1.02482,1.02507,1.02439,1.02494
2022-08-04 23:00:00+00:00,1863,True,1.02492,1.02532,1.02469,1.02484

In [62]:
api.get_history("EUR_USD", "2022-08-03", "2022-08-05", "H12", "A")

,volume,complete,o,h,l,c
time,,,,,,
2022-08-02 21:00:00+00:00,51042,True,1.01694,1.01947,1.01508,1.01889
2022-08-03 09:00:00+00:00,75581,True,1.01887,1.02111,1.01235,1.01703
2022-08-03 21:00:00+00:00,37204,True,1.01710,1.01950,1.01550,1.01925
2022-08-04 09:00:00+00:00,75057,True,1.01924,1.02547,1.01612,1.02478
2022-08-04 21:00:00+00:00,35443,True,1.02518,1.02532,1.02192,1.02246

In [63]:
api.get_history("EUR_USD", "2022-08-03", "2022-08-05", "M1", "A")

C:\Users\v-weihaoloh\Anaconda3\envs\anacondabackup\lib\site-packages\tpqoa\tpqoa.py:161: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(batch)
C:\Users\v-weihaoloh\Anaconda3\envs\anacondabackup\lib\site-packages\tpqoa\tpqoa.py:161: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(batch)

,volume,complete,o,h,l,c
time,,,,,,
2022-08-03 00:00:00+00:00,147,True,1.01575,1.01609,1.01572,1.01583
2022-08-03 00:01:00+00:00,112,True,1.01585,1.01600,1.01583,1.01588
2022-08-03 00:02:00+00:00,120,True,1.01586,1.01621,1.01586,1.01621
2022-08-03 00:03:00+00:00,108,True,1.01620,1.01626,1.01607,1.01615
2022-08-03 00:04:00+00:00,114,True,1.01615,1.01630,1.01608,1.01627
...,...,...,...,...,...,...
2022-08-04 23:55:00+00:00,36,True,1.02497,1.02497,1.02481,1.02482
2022-08-04 23:56:00+00:00,28,True,1.02483,1.02489,1.02483,1.02489
2022-08-04 23:57:00+00:00,28,True,1.02487,1.02487,1.02482,1.02484
2022-08-04 23:58:00+00:00,26,True,1.02484,1.02486,1.02482,1.02485
2022-08-04 23:59:00+00:00,35,True,1.02484,1.02494,1.02483,1.02484

In [64]:
api.get_history("EUR_USD", "2022-08-03", "2022-08-04", "S5", "A")

C:\Users\v-weihaoloh\Anaconda3\envs\anacondabackup\lib\site-packages\tpqoa\tpqoa.py:161: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(batch)
C:\Users\v-weihaoloh\Anaconda3\envs\anacondabackup\lib\site-packages\tpqoa\tpqoa.py:161: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(batch)
C:\Users\v-weihaoloh\Anaconda3\envs\anacondabackup\lib\site-packages\tpqoa\tpqoa.py:161: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(batch)
C:\Users\v-weihaoloh\Anaconda3\envs\anacondabackup\lib\site-packages\tpqoa\tpqoa.py:161: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(batch)
C:\Users\v-weihaoloh\Anaconda3\envs\anacondabackup\lib\site-packages\tpqoa\tpqoa.py:161: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(batch)
C:\Users\v-weihaoloh\Anaconda3\envs\anacondabackup\lib\site-packages\tpqoa\tpqoa.py:161: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(batch)

,volume,complete,o,h,l,c
time,,,,,,
2022-08-03 00:00:00+00:00,28,True,1.01575,1.01593,1.01572,1.01589
2022-08-03 00:00:05+00:00,5,True,1.01588,1.01590,1.01588,1.01590
2022-08-03 00:00:10+00:00,10,True,1.01589,1.01600,1.01589,1.01598
2022-08-03 00:00:15+00:00,17,True,1.01600,1.01600,1.01593,1.01600
2022-08-03 00:00:20+00:00,6,True,1.01600,1.01601,1.01599,1.01600
...,...,...,...,...,...,...
2022-08-03 23:59:30+00:00,6,True,1.01584,1.01586,1.01579,1.01579
2022-08-03 23:59:35+00:00,5,True,1.01579,1.01581,1.01579,1.01580
2022-08-03 23:59:40+00:00,4,True,1.01581,1.01583,1.01579,1.01579
2022-08-03 23:59:45+00:00,4,True,1.01576,1.01580,1.01576,1.01579
2022-08-03 23:59:50+00:00,2,True,1.01577,1.01577,1.01575,1.01575

In [65]:
api.get_instruments()

[('Copper', 'XCU_USD'),
 ('Wheat', 'WHEAT_USD'),
 ('NZD/SGD', 'NZD_SGD'),
 ('US SPX 500', 'SPX500_USD'),
 ('USD/NOK', 'USD_NOK'),
 ('UK 100', 'UK100_GBP'),
 ('AUD/NZD', 'AUD_NZD'),
 ('Silver', 'XAG_USD'),
 ('EUR/HUF', 'EUR_HUF'),
 ('Silver/EUR', 'XAG_EUR'),
 ('Litecoin', 'LTC_USD'),
 ('Silver/GBP', 'XAG_GBP'),
 ('NZD/USD', 'NZD_USD'),
 ('USD/CNH', 'USD_CNH'),
 ('CHF/ZAR', 'CHF_ZAR'),
 ('GBP/NZD', 'GBP_NZD'),
 ('US 10Y T-Note', 'USB10Y_USD'),
 ('Hong Kong 33', 'HK33_HKD'),
 ('US 5Y T-Note', 'USB05Y_USD'),
 ('US 2Y T-Note', 'USB02Y_USD'),
 ('Bund', 'DE10YB_EUR'),
 ('US Russ 2000', 'US2000_USD'),
 ('US T-Bond', 'USB30Y_USD'),
 ('USD/CAD', 'USD_CAD'),
 ('ZAR/JPY', 'ZAR_JPY'),
 ('Silver/JPY', 'XAG_JPY'),
 ('Ether', 'ETH_USD'),
 ('SGD/JPY', 'SGD_JPY'),
 ('GBP/ZAR', 'GBP_ZAR'),
 ('USD/JPY', 'USD_JPY'),
 ('EUR/TRY', 'EUR_TRY'),
 ('Bitcoin', 'BTC_USD'),
 ('EUR/CZK', 'EUR_CZK'),
 ('EUR/JPY', 'EUR_JPY'),
 ('Taiwan Index', 'TWIX_USD'),
 ('AUD/SGD', 'AUD_SGD'),
 ('Silver/NZD', 'XAG_NZD'),
 ('West Texas Oil', 'WTICO_USD'),
 ('Silver/AUD', 'XAG_AUD'),
 ('EUR/NZD', 'EUR_NZD'),
 ('GBP/HKD', 'GBP_HKD'),
 ('CHF/JPY', 'CHF_JPY'),
 ('Gold/AUD', 'XAU_AUD'),
 ('EUR/HKD', 'EUR_HKD'),
 ('Gold/HKD', 'XAU_HKD'),
 ('Gold/JPY', 'XAU_JPY'),
 ('USD/THB', 'USD_THB'),
 ('GBP/CHF', 'GBP_CHF'),
 ('CAD/JPY', 'CAD_JPY'),
 ('NZD/CHF', 'NZD_CHF'),
 ('Spain 35', 'ESPIX_EUR'),
 ('AUD/HKD', 'AUD_HKD'),
 ('Silver/HKD', 'XAG_HKD'),
 ('USD/CHF', 'USD_CHF'),
 ('Silver/CHF', 'XAG_CHF'),
 ('Bitcoin Cash', 'BCH_USD'),
 ('AUD/USD', 'AUD_USD'),
 ('GBP/JPY', 'GBP_JPY'),
 ('USD/TRY', 'USD_TRY'),
 ('US Nas 100', 'NAS100_USD'),
 ('TRY/JPY', 'TRY_JPY'),
 ('USD/SGD', 'USD_SGD'),
 ('EUR/SEK', 'EUR_SEK'),
 ('HKD/JPY', 'HKD_JPY'),
 ('AUD/CHF', 'AUD_CHF'),
 ('Gold/Silver', 'XAU_XAG'),
 ('SGD/CHF', 'SGD_CHF'),
 ('Soybeans', 'SOYBN_USD'),
 ('Corn', 'CORN_USD'),
 ('USD/PLN', 'USD_PLN'),
 ('GBP/AUD', 'GBP_AUD'),
 ('Gold/SGD', 'XAU_SGD'),
 ('AUD/JPY', 'AUD_JPY'),
 ('EUR/ZAR', 'EUR_ZAR'),
 ('China H Shares', 'CHINAH_HKD'),
 ('Singapore 30', 'SG30_SGD'),
 ('EUR/USD', 'EUR_USD'),
 ('EUR/CAD', 'EUR_CAD'),
 ('USD/HUF', 'USD_HUF'),
 ('Netherlands 25', 'NL25_EUR'),
 ('EUR/CHF', 'EUR_CHF'),
 ('UK 10Y Gilt', 'UK10YB_GBP'),
 ('NZD/CAD', 'NZD_CAD'),
 ('EUR/SGD', 'EUR_SGD'),
 ('USD/INR', 'USD_INR'),
 ('Gold/NZD', 'XAU_NZD'),
 ('Gold/GBP', 'XAU_GBP'),
 ('NZD/JPY', 'NZD_JPY'),
 ('CHF/HKD', 'CHF_HKD'),
 ('Australia 200', 'AU200_AUD'),
 ('USD/DKK', 'USD_DKK'),
 ('EUR/AUD', 'EUR_AUD'),
 ('Gold/CAD', 'XAU_CAD'),
 ('Gold/CHF', 'XAU_CHF'),
 ('Japan 225', 'JP225_USD'),
 ('Silver/CAD', 'XAG_CAD'),
 ('USD/ZAR', 'USD_ZAR'),
 ('USD/CZK', 'USD_CZK'),
 ('China A50', 'CN50_USD'),
 ('Europe 50', 'EU50_EUR'),
 ('Silver/SGD', 'XAG_SGD'),
 ('France 40', 'FR40_EUR'),
 ('GBP/SGD', 'GBP_SGD'),
 ('USD/SEK', 'USD_SEK'),
 ('USD/MXN', 'USD_MXN'),
 ('GBP/USD', 'GBP_USD'),
 ('EUR/DKK', 'EUR_DKK'),
 ('Natural Gas', 'NATGAS_USD'),
 ('CAD/CHF', 'CAD_CHF'),
 ('EUR/GBP', 'EUR_GBP'),
 ('CAD/HKD', 'CAD_HKD'),
 ('Switzerland 20', 'CH20_CHF'),
 ('Brent Crude Oil', 'BCO_USD'),
 ('EUR/NOK', 'EUR_NOK'),
 ('Gold', 'XAU_USD'),
 ('Palladium', 'XPD_USD'),
 ('Platinum', 'XPT_USD'),
 ('GBP/CAD', 'GBP_CAD'),
 ('Gold/EUR', 'XAU_EUR'),
 ('Germany 30', 'DE30_EUR'),
 ('NZD/HKD', 'NZD_HKD'),
 ('GBP/PLN', 'GBP_PLN'),
 ('US Wall St 30', 'US30_USD'),
 ('Japan 225 (JPY)', 'JP225Y_JPY'),
 ('EUR/PLN', 'EUR_PLN'),
 ('Sugar', 'SUGAR_USD'),
 ('AUD/CAD', 'AUD_CAD'),
 ('USD/HKD', 'USD_HKD'),
 ('CAD/SGD', 'CAD_SGD')]

In [66]:
api.get_history("SPX500_USD", "2022-08-03", "2022-08-04", "H1", "A")

                           volume  complete       o       h       l       c
time
2022-08-03 00:00:00+00:00    2163      True  4091.1  4095.4  4082.4  4087.9
2022-08-03 01:00:00+00:00    2033      True  4087.6  4098.4  4087.1  4095.9
2022-08-03 02:00:00+00:00    1212      True  4096.4  4100.6  4094.1  4097.4
2022-08-03 03:00:00+00:00     878      True  4097.4  4099.4  4095.6  4097.4
2022-08-03 04:00:00+00:00     726      True  4097.1  4102.9  4096.6  4098.4
2022-08-03 05:00:00+00:00    1089      True  4098.6  4104.4  4098.4  4102.4
2022-08-03 06:00:00+00:00    1162      True  4101.6  4105.6  4098.6  4100.9
2022-08-03 07:00:00+00:00    3444      True  4100.6  4101.6  4092.4  4095.4
2022-08-03 08:00:00+00:00    1731      True  4095.1  4102.4  4090.6  4100.1
2022-08-03 09:00:00+00:00    1333      True  4100.1  4111.4  4098.9  4106.9
2022-08-03 10:00:00+00:00    1271      True  4106.9  4110.1  4104.1  4106.9
2022-08-03 11:00:00+00:00    1294      True  4106.6  4113.4  4105.1  4111.1
2022-08-03 12:00:00+00:00    1383      True  4110.9  4120.4  4109.1  4116.9
2022-08-03 13:00:00+00:00    4940      True  4117.1  4127.6  4110.6  4125.8
2022-08-03 14:00:00+00:00    6401      True  4122.8  4135.1  4112.3  4126.6
2022-08-03 15:00:00+00:00    3755      True  4126.8  4145.8  4124.8  4144.8
2022-08-03 16:00:00+00:00    2642      True  4145.1  4157.6  4137.6  4154.6
2022-08-03 17:00:00+00:00    1960      True  4154.3  4159.1  4150.8  4156.8
2022-08-03 18:00:00+00:00    2123      True  4156.8  4163.3  4153.6  4159.3
2022-08-03 19:00:00+00:00    2498      True  4158.8  4167.8  4152.3  4154.8
2022-08-03 20:00:00+00:00     632      True  4155.1  4155.1  4148.4  4150.1
2022-08-03 22:00:00+00:00     468      True  4149.2  4151.2  4147.2  4150.7
2022-08-03 23:00:00+00:00     439      True  4150.7  4151.0  4147.7  4147.7

## Streaming high-frequency real-time Data

In [71]:
api.stream_data('EUR_USD', stop=20)

2022-09-14T12:46:06.485065278Z 0.99983 0.99992
2022-09-14T12:46:07.202051582Z 0.99984 0.99994
2022-09-14T12:46:07.462142626Z 0.99991 1.0
2022-09-14T12:46:07.617935760Z 0.99995 1.00005
2022-09-14T12:46:07.949039666Z 0.99991 1.00001
2022-09-14T12:46:08.485643475Z 0.99992 1.00003
2022-09-14T12:46:08.600025385Z 0.99995 1.00005
2022-09-14T12:46:09.051829192Z 0.99993 1.00003
2022-09-14T12:46:09.481146469Z 0.9999 1.0
2022-09-14T12:46:09.729002181Z 0.99994 1.00002
2022-09-14T12:46:09.948675266Z 0.99992 1.00002
2022-09-14T12:46:10.262377413Z 0.99995 1.00004
2022-09-14T12:46:10.734615566Z 0.99997 1.00007
2022-09-14T12:46:11.517587754Z 0.99995 1.00005
2022-09-14T12:46:12.259239429Z 0.9999 0.99999
2022-09-14T12:46:12.454799567Z 0.99987 0.99997
2022-09-14T12:46:12.722885118Z 0.99987 0.99997
2022-09-14T12:46:13.267069692Z 0.9999 0.99999
2022-09-14T12:46:13.480122872Z 0.99989 1.0
2022-09-14T12:46:13.980844177Z 0.99997 1.00008

## Creating Orders and Executing Trades

In [98]:
help(api.create_order)

Help on method create_order in module tpqoa.tpqoa:

create_order(instrument, units, sl_distance=0.01) method of tpqoa.tpqoa.tpqoa instance
    Places order with Oanda.

    Parameters
    ==========
    instrument: string
        valid instrument name
    units: int
        number of units of instrument to be bought
        (positive int, eg 'units=50')
        or to be sold (negative int, eg 'units=-100')
    sl_distance: float
        stop loss distance price, mandatory eg in Germany

In [97]:
api.create_order(instrument = "EUR_USD", units = 100000, sl_distance= 0.1)

 {'id': '31', 'time': '2022-09-14T13:04:45.083778279Z', 'userID': 23224294, 'accountID': '101-003-23224294-001', 'batchID': '30', 'requestID': '43004598533797126', 'type': 'ORDER_FILL', 'orderID': '30', 'instrument': 'EUR_USD', 'units': '100000.0', 'gainQuoteHomeConversionFactor': '1.3978755', 'lossQuoteHomeConversionFactor': '1.4119245', 'price': 0.99998, 'fullVWAP': 0.99998, 'fullPrice': {'type': 'PRICE', 'bids': [{'price': 0.9999, 'liquidity': '1000000'}, {'price': 0.99989, 'liquidity': '2000000'}, {'price': 0.99988, 'liquidity': '2000000'}, {'price': 0.99986, 'liquidity': '5000000'}], 'asks': [{'price': 0.99998, 'liquidity': '1000000'}, {'price': 1.0, 'liquidity': '2000000'}, {'price': 1.00001, 'liquidity': '2000000'}, {'price': 1.00002, 'liquidity': '5000000'}], 'closeoutBid': 0.99986, 'closeoutAsk': 1.00002}, 'reason': 'MARKET_ORDER', 'pl': '8.3873', 'financing': '0.0', 'commission': '0.0', 'guaranteedExecutionFee': '0.0', 'accountBalance': '100044.7412', 'tradesClosed': [{'tradeID': '28', 'units': '100000.0', 'price': 0.99998, 'realizedPL': '8.3873', 'financing': '0.0', 'guaranteedExecutionFee': '0.0', 'halfSpreadCost': '5.6196'}], 'halfSpreadCost': '5.6196'}

In [96]:
api.create_order(instrument = "EUR_USD", units = -100000, sl_distance= 0.01)

 {'id': '28', 'time': '2022-09-14T13:03:54.422497715Z', 'userID': 23224294, 'accountID': '101-003-23224294-001', 'batchID': '27', 'requestID': '24990199812139123', 'type': 'ORDER_FILL', 'orderID': '27', 'instrument': 'EUR_USD', 'units': '-100000.0', 'gainQuoteHomeConversionFactor': '1.39778595', 'lossQuoteHomeConversionFactor': '1.41183405', 'price': 1.00004, 'fullVWAP': 1.00004, 'fullPrice': {'type': 'PRICE', 'bids': [{'price': 1.00004, 'liquidity': '1000000'}, {'price': 1.00003, 'liquidity': '2000000'}, {'price': 1.00002, 'liquidity': '2000000'}, {'price': 1.0, 'liquidity': '5000000'}], 'asks': [{'price': 1.00014, 'liquidity': '1000000'}, {'price': 1.00016, 'liquidity': '2000000'}, {'price': 1.00017, 'liquidity': '2000000'}, {'price': 1.00018, 'liquidity': '5000000'}], 'closeoutBid': 1.0, 'closeoutAsk': 1.00018}, 'reason': 'MARKET_ORDER', 'pl': '0.0', 'financing': '0.0', 'commission': '0.0', 'guaranteedExecutionFee': '0.0', 'accountBalance': '100036.3539', 'tradeOpened': {'tradeID': '28', 'units': '-100000.0', 'price': 1.00004, 'guaranteedExecutionFee': '0.0', 'halfSpreadCost': '7.024', 'initialMarginRequired': '7024.5'}, 'halfSpreadCost': '7.024'}

In [74]:
api.get_account_summary()

{'id': '101-003-23224294-001',
 'alias': 'Primary',
 'currency': 'SGD',
 'balance': '100036.3539',
 'createdByUserID': 23224294,
 'createdTime': '2022-09-13T12:16:27.974338285Z',
 'guaranteedStopLossOrderMode': 'ALLOWED',
 'pl': '-231.3561',
 'resettablePL': '-231.3561',
 'resettablePLTime': '0',
 'financing': '0.0',
 'commission': '0.0',
 'guaranteedExecutionFees': '0.0',
 'marginRate': '0.05',
 'openTradeCount': 0,
 'openPositionCount': 0,
 'pendingOrderCount': 0,
 'hedgingEnabled': False,
 'unrealizedPL': '0.0',
 'NAV': '100036.3539',
 'marginUsed': '0.0',
 'marginAvailable': '100036.3539',
 'positionValue': '0.0',
 'marginCloseoutUnrealizedPL': '0.0',
 'marginCloseoutNAV': '100036.3539',
 'marginCloseoutMarginUsed': '0.0',
 'marginCloseoutPercent': '0.0',
 'marginCloseoutPositionValue': '0.0',
 'withdrawalLimit': '100036.3539',
 'marginCallMarginUsed': '0.0',
 'marginCallPercent': '0.0',
 'lastTransactionID': '26'}

In [92]:
trade_record = api.get_transactions()

In [94]:
df1 = pd.DataFrame.from_dict(trade_record)

In [95]:
df1

,id,time,userID,accountID,batchID,requestID,type,divisionID,siteID,accountUserID,...,commission,guaranteedExecutionFee,tradeOpened,halfSpreadCost,tradeClose,tradesClosed,stopLossOnFill,tradeID,distance,triggerCondition
0,1,2022-09-13T12:16:27.974338285Z,23224294,101-003-23224294-001,1,1790400879411534379,CREATE,3.0,101.0,23224294.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2022-09-13T12:16:27.974338285Z,23224294,101-003-23224294-001,1,1790400879411534379,CLIENT_CONFIGURE,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,2022-09-13T12:16:28.610415651Z,23224294,101-003-23224294-001,3,1754372082395703986,TRANSFER_FUNDS,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,2022-09-13T12:46:17.546443701Z,23224294,101-003-23224294-001,4,24989832991104862,MARKET_ORDER,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,2022-09-13T12:46:17.546443701Z,23224294,101-003-23224294-001,4,24989832991104862,ORDER_FILL,NaN,NaN,NaN,...,0.0,0.0,"{'tradeID': '5', 'units': '100000.0', 'price':...",7.0075,NaN,NaN,NaN,NaN,NaN,NaN
5,6,2022-09-13T12:46:29.241161103Z,23224294,101-003-23224294-001,6,24989833041456817,MARKET_ORDER,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'tradeID': '5', 'units': '100000'}",NaN,NaN,NaN,NaN,NaN
6,7,2022-09-13T12:46:29.241161103Z,23224294,101-003-23224294-001,6,24989833041456817,ORDER_FILL,NaN,NaN,NaN,...,0.0,0.0,NaN,6.3069,NaN,"[{'tradeID': '5', 'units': '-100000.0', 'price...",NaN,NaN,NaN,NaN
7,8,2022-09-13T12:46:46.560434481Z,23224294,101-003-23224294-001,8,24989833112790460,MARKET_ORDER,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,2022-09-13T12:46:46.560434481Z,23224294,101-003-23224294-001,8,24989833112790460,ORDER_FILL,NaN,NaN,NaN,...,0.0,0.0,"{'tradeID': '9', 'units': '-100000.0', 'price'...",5.6072,NaN,NaN,NaN,NaN,NaN,NaN
9,10,2022-09-13T12:47:32.792643366Z,23224294,101-003-23224294-001,10,24989833305806945,MARKET_ORDER,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'tradeID': '9', 'units': '100000'}",NaN,NaN,NaN,NaN,NaN
10,11,2022-09-13T12:47:32.792643366Z,23224294,101-003-23224294-001,10,24989833305806945,ORDER_FILL,NaN,NaN,NaN,...,0.0,0.0,NaN,6.3067,NaN,"[{'tradeID': '9', 'units': '100000.0', 'price'...",NaN,NaN,NaN,NaN
11,12,2022-09-13T12:47:41.693728335Z,23224294,101-003-23224294-001,12,24989833343570740,MARKET_ORDER,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,2022-09-13T12:47:41.693728335Z,23224294,101-003-23224294-001,12,24989833343570740,ORDER_FILL,NaN,NaN,NaN,...,0.0,0.0,"{'tradeID': '13', 'units': '100000.0', 'price'...",7.007,NaN,NaN,NaN,NaN,NaN,NaN
13,14,2022-09-13T12:51:26.902007998Z,23224294,101-003-23224294-001,14,24989834287678741,MARKET_ORDER,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'tradeID': '13', 'units': '100000'}",NaN,NaN,NaN,NaN,NaN
14,15,2022-09-13T12:51:26.902007998Z,23224294,101-003-23224294-001,14,24989834287678741,ORDER_FILL,NaN,NaN,NaN,...,0.0,0.0,NaN,7.011,NaN,"[{'tradeID': '13', 'units': '-100000.0', 'pric...",NaN,NaN,NaN,NaN
15,16,2022-09-13T12:52:23.614189880Z,23224294,101-003-23224294-001,16,1790400888454755760,TRANSFER_FUNDS,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,2022-09-13T12:52:33.947799140Z,23224294,101-003-23224294-001,17,1772386489986372770,TRANSFER_FUNDS,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,2022-09-13T12:53:15.384090941Z,23224294,101-003-23224294-001,18,1754372091652836888,TRANSFER_FUNDS,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19,2022-09-13T12:54:42.504414039Z,23224294,101-003-23224294-001,19,1790400889037784203,TRANSFER_FUNDS,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20,2022-09-13T12:55:29.807801056Z,23224294,101-003-23224294-001,20,1772386490724593799,TRANSFER_FUNDS,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21,2022-09-14T12:49:28.386397730Z,23224294,101-003-23224294-001,21,79033391706755640,MARKET_ORDER,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"{'distance': '0.1', 'timeInForce': 'GTC'}",NaN,NaN,NaN
21,22,2022-09-14T12:49:28.386397730Z,23224294,101-003-23224294-001,21,79033391706755640,ORDER_FILL,NaN,NaN,NaN,...,0.0,0.0,"{'tradeID': '22', 'units': '100000.0', 'price'...",5.6198,NaN,NaN,NaN,NaN,NaN,NaN
22,23,2022-09-14T12:49:28.386397730Z,23224294,101-003-23224294-001,21,79033391706755640,STOP_LOSS_ORDER,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22,0.1,DEFAULT
23,24,2022-09-14T12:52:08.893849884Z,23224294,101-003-23224294-001,24,24990196849808985,MARKET_ORDER,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"{'distance': '0.1', 'timeInForce': 'GTC'}",NaN,NaN,NaN
24,25,2022-09-14T12:52:08.893849884Z,23224294,101-003-23224294-001,24,24990196849808985,ORDER_FILL,NaN,NaN,NaN,...,0.0,0.0,NaN,6.3221,NaN,"[{'tradeID': '22', 'units': '-100000.0', 'pric...",NaN,NaN,NaN,NaN
25,26,2022-09-14T12:52:08.893849884Z,23224294,101-003-23224294-001,24,24990196849808985,ORDER_CANCEL,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN